version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: taggy-bit_web_1  # Ensure this matches the web service name
      APP_PORT: 3000
  
  web:
    image: diogocostaeu/taggy-bit:v0.0.2
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3031:3000
